version: '2'

services:
  mysql:
    container_name: 'mysql'
    image: mysql:8
    environment:
      MYSQL_DATABASE: 'todo'
      MYSQL_ROOT_PASSWORD: '123'
    volumes:
      - './data/mysql/data/:/var/lib/mysql'
      - './data/mysql/conf:/etc/mysql/conf.d'
    ports:
      - 3306:3306
